spring:
    application:
        name: notification
    datasource:
        url: jdbc:mysql://localhost:3357/micrologs
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: spec
        password: spec
    rabbitmq:
        host: localhost
        port: 5672
        username: admin
        password: admin
        listener:
            simple:
                prefetch: 50

server:
    port: 8084

cassandra:
    prop:
        host: localhost
        port: 9042
        datacenter: spec
